filter:
    paths: ["src/"]
checks:
    php: true
build:
    nodes:
        php72:
            environment:
                php:
                    version: "7.2"
    tests:
        override:
            - command: php-scrutinizer-run
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage-clover'
                coverage:
                    file: 'coverage-clover'
                    format: 'clover'
